version: "3.8"
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: currExch
      POSTGRES_PASSWORD: cUrrE6C9g
      POSTGRES_DB: exchange_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - FIXER_API_KEY=ac770a1941584e4045097a816536da4e
      - DATABASE_URL=postgresql://currExch:cUrrE6C9g@db:5432/exchange_db
      - SPREAD_PERCENT=1.5

volumes:
  pgdata:

